osx_image: xcode9.3
language: swift
branches:
  only:
    - develop
    - master
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwedishSSN.xcworkspace -scheme SwedishSSN-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.3' xcpretty -c
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)